### ISSUE TITLE
Cant get Ledger to confirm Zcoin (electrum) transaction

### ISSUE THREAD

**Issue by adamsa1** [zcoinofficial/electrum-xzc#28]
I have tried so many different way to get the ability to transfer my Zcoin from Electrum wallet 3.3.6v and still cant get the coins out of electrum. My ledger does give the option to approve the transaction. I tried making a new wallet but nothing. The address I'm using in electrum is from my mining profits. I tried to follow the directions on "Receiving mining profits of Ledger help and still doesn't confirm. Any guidance please???

**Comment by justanwar** [comment]
![image](https://user-images.githubusercontent.com/42809091/61594743-e2c57380-ac21-11e9-9aa0-b3733e8be333.png)


In Electrum-xzc, select View -> Show coins. Right-click on only one entry and select Spend, then try sending this one out. Your Ledger should prompt you almost immediately.

If that is successful, try Ctrl+Left Click in the Coins tab to select a maximum of five entries. Then right-click and select Spend. You will now notice a bit of sluggishness while waiting for the Ledger to show the transaction approval prompt. 

You can try with 10, 15 or 20 entries at once, but I would not recommend going past 20 since the Ledger will time out.

**Comment by justanwar** [comment]
Feel free to reopen if issue persists.

**Comment by a-bezrukov** [comment]
@justanwar, thanks for describing this!
@adamsa1, here is the initial thread about this problem: https://github.com/zcoinofficial/electrum-xzc/issues/21#issuecomment-502381336 . There are 2 ways described - consolidation and using your wallet without Ledger. Both are working. Please post here if need be.
