### ISSUE TITLE
The transaction was rejected because it is too large (in bytes).

### ISSUE THREAD

**Issue by HeartlessNoob** [zcoinofficial/electrum-xzc#41]
Hello. 
Electrum-XZC I use it for a long time. And now I can’t make a payment from my wallet. Error:"The server returned an error when broadcasting the transaction. Consider trying to connect to a different server, or updating Electrum. The transaction was rejected because it is too large (in bytes)." 
The size of the transaction in bytes is really large: more than 80 Кб. Wallet Version: Electrum-XZC 3.3.8 addition 3. 
I tried the portable version, the version is older. The result is the same. Made a new wallet (new address), payments go away from him normally. The problem is with this XZC address of mine. How to get zcoin out of there? 
Help me please.

**Comment by justanwar** [comment]
How many inputs does this transaction has? Try limiting it to only five inputs and sending out that transaction.

**Comment by HeartlessNoob** [comment]
Thanks for the answer.
> How many inputs does this transaction has?

561

> Try limiting it to only five inputs and sending out that transaction.

Tell me, please, how to do this? Or where to read. Could not find quickly.

**Comment by justanwar** [comment]
![image](https://user-images.githubusercontent.com/42809091/61594743-e2c57380-ac21-11e9-9aa0-b3733e8be333.png)


In Electrum-xzc, select View -> Show coins. Right-click on only one entry and select Spend, then try sending this one out. Your Ledger should prompt you almost immediately.

If that is successful, try Ctrl+Left Click in the Coins tab to select a maximum of five entries. Then right-click and select Spend. You will now notice a bit of sluggishness while waiting for the Ledger to show the transaction approval prompt. 

You can try with 10, 15 or 20 entries at once, but I would not recommend going past 20 since the Ledger will time out.

_Originally posted by @justanwar in https://github.com/zcoinofficial/electrum-xzc/issues/28#issuecomment-513573689_

**Comment by HeartlessNoob** [comment]
justanwar, thank you so much for the quick and comprehensive, and most importantly effective answer!
